on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: QiubyZ/apk-autorelease@v54  # Panggil custom action
        with:
          gradle_cmd: 'assembleDebug'
          tag: 'Release'
          body_release: 'Aplikasi ini otomatis dirilis.'
          file_output: './app/build/outputs/apk/debug/app-debug.apk'
