name: Android Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: QiubyZ/apk-autorelease@v72
        with:
          gradle_cmd: 'assembleRelease' # this is will write apk filename /app-release-unsigned.apk
          tag: 'Production'
          body_release: 'Aplikasi versi produksi dirilis.'
          file_output: './app/build/outputs/apk/release/app-release-unsigned.apk'
          # Sesuaikan lokasi
          
      - name: CHECK RESULT *.APK
        run: ls -l -a ./app/build/outputs/apk/release
      
        
