name: Android Release

env:
  apk_file: './app/build/outputs/apk/debug/app-debug.apk'
    

on:
  push:
    branches:
      - main
      - Dev
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setting JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Memberikan Perizinan gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
        shell: bash
      
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ env.apk_file }}
        
      - name: Buat Rilis Baru
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.repository.name }}
          name: ${{ github.event.repository.name }}
          files: ${{ env.apk_file }}
          draft: true
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}         
          
