name: Android Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    #permissions:
      #contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: QiubyZ/apk-autorelease@v76
        with:
          gradle_cmd: 'assembleDebug' # this is will write apk filename /app-release-unsigned.apk
          tag: 'Production'
          body_release: 'Aplikasi versi produksi dirilis.'
          file_output: './app/build/outputs/apk/debug/app-debug.apk'
          
        

