name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Release APK
      uses: QiubyZ/apk-autorelease@v50
